version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.6

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt

      - run:
          name: Run application

          command:
            python main.py
      - run:
          name: Check output file generated
          command:
            python main.py

      - run:
          name: Check output file generated
          command: |
            ls -alt files
            FILE=$(pwd)/files/output.txt
            echo "$File"
#            if test -f "$FILE"; then
#              echo "$FILE exists."
#              exit 0
#            exit 1

workflows:
  First:
    jobs:
      - build-and-test